"""second_migration_for_pytest

Revision ID: 0188141ef812
Revises: 238b93b3b5ba
Create Date: 2023-01-15 18:08:54.151803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0188141ef812'
down_revision = '238b93b3b5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
